ip: localhost
server:
  port: 8080

# 短链接服务配置
smartUrl:
  # 服务域名
  domainName: localhost:${server.port}
  # 短链接解码失败，重定向百度
  errorPage: https://www.baidu.com

  
springdoc:
  api-docs:
    #是否开启文档功能
    enabled: true
    #swagger后端请求地址
    path: /api-docs
  swagger-ui:
    #自定义swagger前端请求路径，/test 输入http：127.0.0.1:8080/test会自动重定向到swagger页面
    path: /swagger-ui
  #包扫描路径
  packages-to-scan: com.huang.shorturl.controller
  #这里定义了两个分组，可定义多个，也可以不定义
  group-configs:
      #分组名
    - group: 短连接服务
      #按包路径匹配
      packagesToScan: com.huang.shorturl.controller
  
#是否开启swagger
swagger: 
  enable: true
  